### ISSUE TITLE
[QUEST] Lou's Parting Thoughts

### ISSUE THREAD

**Issue by Redanski** [GameFreedomGG/Maelstrom#378]
[/]: # (REMBEMBER! Add links to things related to the bug using for example http://wowhead.com)

**Description:**
Lou's Parting Thoughts
After you eavesdropped on the Thugs and leave their melee Range they wont attack.
They get blue names and just stay there, quest wont complete until you run into melee range.

**How to reproduce:**
Eavesdrop on them go on approx 25y range.

**How it should work:**
They should attack you.
Quest completion should be awarded after you killed them iirc.

**Wowhead links:**
https://www.wowhead.com/quest=26232/lous-parting-thoughts

**Comment by HerodDev** [comment]
add wowhead links

**Comment by HerodDev** [comment]
Also from other issue:

Description:
The 4 NPCs for the quest that u have to kill only spawn if u run on their spawn position.

How to reproduce:
Start the quest and u wont see the Mobs until u stay right on their spawn.

How it should work:
Normally after starting the quest the mobs should be spawned already.

**Comment by HerodDev** [comment]
From other issue:
Description:
One of these Thugs did not become hostile, only 3 out of 4 attacked me.
Additionally, 2 of the 4 became hostile first, 1 became hostile slightly after the first 2 and 1 just stood there. Not sure if the one who did not attack at all perhaps was because he was the one furthest away meaning you need to be close.

How it should work:
All 4 should attack you and become hostile at the same time.
